Samuel Kersebet HWK1

1.
a) <One> , <Group> , <Var>
b) a, b, c, [,], , ,(,)
c) <group>
d)
                <Group>
                   |
            ---------------
           /  |    |   |    \
          [ <One> , <Group>  ]    
         /   |   \      | 
        ( <Group> )      \
             |          -------------
           <Var>      /  |   |    |    \
             |       [ <One> , <Group>  ]  
             a           |        |
                       <Var>     <One>
                         |         |
                         b       <Var>
                                   |
                                   c

2. <Str> ::= xy | x<Str>y

3. 
<statement> ::= <exp>
<exp> ::= <aexp> | <bexp> | <cexp>
<aexp> ::= <num> | "(" <aexp> ")" | <aexp> <mop> <aexp> | <var> 
<cexp> ::= <bexp> | <cexp> <eqop> <cexp> | <cexp> <bop> <cexp>
<bexp> ::= "(" <bexp> ")" | "!" <bexp> | <bexp> <bop> <bexp> | <bexp> <eqop> <bexp> | <aexp> <eqop> <aexp> | <var>
<num> ::= [0-9]+
<var> ::= [a-z]+ | [A-Z]+
<mop> ::= "+" | "-" | "*" | "/"
<eqop> ::= "<" | ">" | "=="
<bop> ::= "&&" | "||"